language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:28msec/boost
  - sudo apt-get update
  - sudo apt-get install  -qq boost1.50

before_script:
  cmake .

script:
  make

branches:
  only:
    - master
notifications:
  recipients:
    - microcaicai@gmail.com
  email:
    on_success: change
    on_failure: always

