language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install wget
  - git submodule init
  - git submodule update
  - wget http://jaist.dl.sourceforge.net/boost/boost_1_54_0.tar.bz2
  - tar -xf boost_1_54_0.tar.bz2
  - ( cd boost_1_54_0  && ./bootstrap.sh --prefix=/usr --with-libraries=date_time,filesystem,exception,log,locale,random,regex,program_options,system,thread && sudo ./b2 -j2 link=static install )

before_script:
  cmake -DENABLE_LUA=on  .

script:
  make

notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

