language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install  -qq boost1.53
  - sudo apt-get install libluajit-5.1-dev
  - sudo apt-get install libluabind-dev
  - git submodule init
  - git submodule update

before_script:
  cmake -DENABLE_LUA=on  -DINTERNAL_LUABIND=off .

script:
  make

notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

